services:
  srp:
    build:
      context: ..
      dockerfile: srp/Dockerfile
    container_name: srp
    volumes:
      - ./client.toml:/app/client.toml:ro
    depends_on:
      - srps
    ports:
      - "443:443"
    networks:
      internet:
        ipv4_address: 172.25.0.2

  srps:
    build:
      context: ..
      dockerfile: srps/Dockerfile
    container_name: srps
    volumes:
      - ./server.toml:/app/server.toml:ro
    depends_on:
      - web
    networks:
      internet:
        ipv4_address: 172.25.0.3
      home:

  web:
    image: caddy
    container_name: web
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
    - home

networks:
  internet:
    ipam:
     config:
       - subnet: 172.25.0.0/24
         gateway: 172.25.0.1
  home:
