name: Rust
permissions:
  contents: read # Globally allow reading the repository contents
  
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Perform Unit Tests
        run: cargo test --release
    
  build:
    name: Build Release Version
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Building
      run: cargo build --release
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: rust-binaries
        path: |
          target/release/srp
          target/release/srps

